"""add ToolboxTalkParticipant table

Revision ID: 464abfb20e3b
Revises: a4971139a253
Create Date: 2025-03-29 10:40:10.829094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '464abfb20e3b'
down_revision: Union[str, None] = 'a4971139a253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toolbox_talk_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('toolbox_talk_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['toolbox_talk_id'], ['generated_toolbox_talks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toolbox_talk_participants_id'), 'toolbox_talk_participants', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_toolbox_talk_participants_id'), table_name='toolbox_talk_participants')
    op.drop_table('toolbox_talk_participants')
    # ### end Alembic commands ###
