"""Add toolbox_talks and related tables

Revision ID: 9da0b5d9da54
Revises: bd9af6a7ba91
Create Date: 2025-03-20 12:05:26.217535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da0b5d9da54'
down_revision: Union[str, None] = 'bd9af6a7ba91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_table('toolbox_talks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('document_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toolbox_talks_id'), 'toolbox_talks', ['id'], unique=False)
    op.create_table('attendees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('toolbox_talk_id', sa.Integer(), nullable=True),
    sa.Column('worker_name', sa.String(), nullable=False),
    sa.Column('worker_email', sa.String(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('attended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['toolbox_talk_id'], ['toolbox_talks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendees_id'), 'attendees', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('toolbox_talk_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['toolbox_talk_id'], ['toolbox_talks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('risks_and_controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('toolbox_talk_id', sa.Integer(), nullable=True),
    sa.Column('risk_description', sa.Text(), nullable=False),
    sa.Column('control_measures', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['toolbox_talk_id'], ['toolbox_talks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_and_controls_id'), 'risks_and_controls', ['id'], unique=False)
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_index(op.f('ix_risks_and_controls_id'), table_name='risks_and_controls')
    op.drop_table('risks_and_controls')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_attendees_id'), table_name='attendees')
    op.drop_table('attendees')
    op.drop_index(op.f('ix_toolbox_talks_id'), table_name='toolbox_talks')
    op.drop_table('toolbox_talks')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
