"""🔄 Add VectorIndex model for FAISS files

Revision ID: a3d60518941f
Revises: 464abfb20e3b
Create Date: 2025-04-05 19:23:39.635664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d60518941f'
down_revision: Union[str, None] = '464abfb20e3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vector_indexes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('toolbox_talk_id', sa.Integer(), nullable=False),
    sa.Column('file_path_index', sa.String(), nullable=False),
    sa.Column('file_path_metadata', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['toolbox_talk_id'], ['generated_toolbox_talks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vector_indexes_id'), 'vector_indexes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vector_indexes_id'), table_name='vector_indexes')
    op.drop_table('vector_indexes')
    # ### end Alembic commands ###
