"""Add toolbox_talk_id to reference_documents

Revision ID: fc521ddecd43
Revises: 2865bc6331d6
Create Date: 2025-03-24 15:18:55.764959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc521ddecd43'
down_revision: Union[str, None] = '2865bc6331d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference_documents', sa.Column('toolbox_talk_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reference_documents', 'generated_toolbox_talks', ['toolbox_talk_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reference_documents', type_='foreignkey')
    op.drop_column('reference_documents', 'toolbox_talk_id')
    # ### end Alembic commands ###
